2025-03-27 15:52:32,845 - INFO - logger - IP: Unknown IP - Camera feed thread started at main.py
2025-03-27 15:52:32,846 - INFO - logger - IP: Unknown IP - Face recognition thread started at main.py
2025-03-27 15:52:32,847 - ERROR - logger - IP: Unknown IP - monitor_brightness function error at day_night.py :Camera disconnected, retrying...
2025-03-27 15:52:32,847 - INFO - logger - IP: Unknown IP - Monitor_brightness thread started at main.py
2025-03-27 15:52:32,976 - INFO - logger - IP: Unknown IP - Database initialized successfully.
2025-03-27 15:52:32,985 - INFO - logger - IP: Unknown IP - Face database initialized successfully.
2025-03-27 15:52:32,986 - INFO - logger - IP: Unknown IP - Databases initialized if not exists at main.py
2025-03-27 15:53:31,459 - CRITICAL - logger - IP: Unknown IP - Error during cleanup using atexit in automatic_camera_functions.py: 'bool' object is not callable
2025-03-27 16:02:32,656 - INFO - logger - IP: Unknown IP - Camera feed thread started at main.py
2025-03-27 16:02:32,657 - INFO - logger - IP: Unknown IP - Face recognition thread started at main.py
2025-03-27 16:02:32,657 - ERROR - logger - IP: Unknown IP - monitor_brightness function error at day_night.py :Camera disconnected, retrying...
2025-03-27 16:02:32,657 - INFO - logger - IP: Unknown IP - Monitor_brightness thread started at main.py
2025-03-27 16:02:32,745 - INFO - logger - IP: Unknown IP - Camera initialized successfully (camera_feed_function at automatic_camera_functions.py).
2025-03-27 16:02:32,745 - INFO - logger - IP: Unknown IP - Database initialized successfully.
2025-03-27 16:02:32,746 - INFO - logger - IP: Unknown IP - Face database initialized successfully.
2025-03-27 16:02:32,746 - INFO - logger - IP: Unknown IP - Databases initialized if not exists at main.py
2025-03-27 16:04:37,967 - CRITICAL - logger - IP: Unknown IP - Error during cleanup function using atexit in automatic_camera_functions.py: 'bool' object is not callable
2025-03-27 16:17:19,479 - INFO - logger - IP: Unknown IP - Camera feed thread started at main.py
2025-03-27 16:17:28,684 - INFO - logger - IP: Unknown IP - Face recognition thread started at main.py
2025-03-27 16:17:33,036 - ERROR - logger - IP: Unknown IP - monitor_brightness function error at day_night.py :Camera disconnected, retrying...
2025-03-27 16:17:33,741 - INFO - logger - IP: Unknown IP - Camera initialized successfully (camera_feed_function at automatic_camera_functions.py).
2025-03-27 16:17:39,102 - INFO - logger - IP: Unknown IP - Monitor_brightness thread started at main.py
2025-03-27 16:18:18,188 - INFO - logger - IP: Unknown IP - Database initialized successfully (users_logs_DB.py).
2025-03-27 16:18:29,827 - INFO - logger - IP: Unknown IP - Face database initialized successfully (face_DB.py).
2025-03-27 16:18:37,838 - INFO - logger - IP: Unknown IP - Databases initialized if not exists (main.py)
2025-03-27 16:19:18,062 - CRITICAL - logger - IP: Unknown IP - Error during cleanup function using atexit in automatic_camera_functions.py: 'bool' object is not callable
2025-03-27 16:34:47,745 - INFO - logger - IP: Unknown IP - Camera feed thread started at main.py
2025-03-27 16:34:47,746 - INFO - logger - IP: Unknown IP - Face recognition thread started at main.py
2025-03-27 16:34:47,746 - INFO - logger - IP: Unknown IP - Monitor_brightness thread started at main.py
2025-03-27 16:34:47,837 - INFO - logger - IP: Unknown IP - Camera initialized successfully (camera_feed_function at automatic_camera_functions.py).
2025-03-27 16:34:47,838 - INFO - logger - IP: Unknown IP - Database initialized successfully (users_logs_DB.py).
2025-03-27 16:34:47,838 - INFO - logger - IP: Unknown IP - Face database initialized successfully (face_DB.py).
2025-03-27 16:34:47,838 - INFO - logger - IP: Unknown IP - Databases initialized if not exists (main.py)
2025-03-27 16:35:29,960 - INFO - logger - IP: Unknown IP - monitor_brightness function loop graciously stopped using atexit (cleanflag at day_night.py).
2025-03-27 16:35:29,960 - CRITICAL - logger - IP: Unknown IP - Error during cleanup function using atexit in automatic_camera_functions.py: 'bool' object is not callable
2025-03-27 16:40:59,303 - INFO - logger - IP: Unknown IP - Camera feed thread started at main.py
2025-03-27 16:40:59,306 - INFO - logger - IP: Unknown IP - Face recognition thread started at main.py
2025-03-27 16:40:59,309 - INFO - logger - IP: Unknown IP - Monitor_brightness thread started at main.py
2025-03-27 16:40:59,410 - INFO - logger - IP: Unknown IP - Camera initialized successfully (camera_feed_function at automatic_camera_functions.py).
2025-03-27 16:40:59,437 - INFO - logger - IP: Unknown IP - Database initialized successfully (users_logs_DB.py).
2025-03-27 16:40:59,438 - INFO - logger - IP: Unknown IP - Face database initialized successfully (face_DB.py).
2025-03-27 16:40:59,438 - INFO - logger - IP: Unknown IP - Databases initialized if not exists (main.py)
2025-03-27 16:45:31,077 - INFO - logger - IP: Unknown IP - Camera feed thread started at main.py
2025-03-27 16:45:34,705 - INFO - logger - IP: Unknown IP - Camera initialized successfully (camera_feed_function at automatic_camera_functions.py).
2025-03-27 16:45:37,860 - INFO - logger - IP: Unknown IP - Face recognition thread started at main.py
2025-03-27 16:45:48,542 - INFO - logger - IP: Unknown IP - Monitor_brightness thread started at main.py
2025-03-27 16:46:15,361 - INFO - logger - IP: Unknown IP - Database initialized successfully (users_logs_DB.py).
2025-03-27 16:46:25,665 - INFO - logger - IP: Unknown IP - Face database initialized successfully (face_DB.py).
2025-03-27 16:46:31,952 - INFO - logger - IP: Unknown IP - Databases initialized if not exists (main.py)
2025-03-27 16:46:44,449 - INFO - logger - IP: Unknown IP - monitor_brightness function loop graciously stopped using atexit (cleanflag at day_night.py).
2025-03-27 16:46:44,449 - CRITICAL - logger - IP: Unknown IP - Error during cleanup function using atexit (automatic_camera_functions.py): 'bool' object is not callable
2025-03-27 16:49:48,742 - INFO - logger - IP: Unknown IP - Camera feed thread started at main.py
2025-03-27 16:49:48,742 - INFO - logger - IP: Unknown IP - Face recognition thread started at main.py
2025-03-27 16:49:48,743 - ERROR - logger - IP: Unknown IP - monitor_brightness function error at day_night.py :Camera disconnected, retrying...
2025-03-27 16:49:48,743 - INFO - logger - IP: Unknown IP - Monitor_brightness thread started at main.py
2025-03-27 16:49:48,829 - INFO - logger - IP: Unknown IP - Camera initialized successfully (camera_feed_function at automatic_camera_functions.py).
2025-03-27 16:49:48,829 - INFO - logger - IP: Unknown IP - Database initialized successfully (users_logs_DB.py).
2025-03-27 16:49:48,830 - INFO - logger - IP: Unknown IP - Face database initialized successfully (face_DB.py).
2025-03-27 16:49:48,830 - INFO - logger - IP: Unknown IP - Databases initialized if not exists (main.py)
2025-03-27 16:50:06,310 - INFO - logger - IP: Unknown IP - monitor_brightness function loop graciously stopped using atexit (cleanflag at day_night.py).
2025-03-27 16:50:06,716 - WARNING - logger - IP: Unknown IP - Camera resources released cleanup function (automatic_camera_functions.py).
